# Generated by Django 3.2 on 2021-04-16 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('document', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('share_status', models.CharField(choices=[('share_all', 'Share publicly'), ('share_friends', 'Share with friends'), ('private', 'Private')], default='private', max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_file', to='merge_app.uploadfile')),
                ('share_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
